# Generated by Django 4.2.2 on 2023-06-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Номер поля')),
                ('event_image', models.ImageField(default=False, upload_to='event_image', verbose_name='Фото события')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('time', models.TimeField(verbose_name='Время события')),
                ('text', models.TextField(verbose_name='Описание события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Бронь события')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Участник')),
            ],
        ),
    ]
