# Generated by Django 4.2.2 on 2023-06-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingevent',
            options={'verbose_name': 'Бронирование события', 'verbose_name_plural': 'Бронирование события'},
        ),
    ]
