# Generated by Django 4.2.2 on 2023-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_bookingevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=False, upload_to='event_images/', verbose_name='Фото события'),
        ),
    ]
