# Generated by Django 4.2.2 on 2023-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_image',
            field=models.ImageField(default=False, upload_to='full_article_images/', verbose_name='Фото новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(default=False, upload_to='preview_article_images/', verbose_name='Фото в шаре'),
        ),
    ]
