version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/core
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vkpdm#gx$&n^!=9(a9a5^^73!ti9yhrdg09854a@uskrancz5o
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

  front:
    container_name: docker_front_green
    restart: always
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile
    volumes:
      - ./frontend:/front_green
      - /front_green/node_modules
    ports:
      - 8080:8080
    expose:
      - 8080

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/core
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vkpdm#gx$&n^!=9(a9a5^^73!ti9yhrdg09854a@uskrancz5o
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    restart: always
    build: .
    command: "celery -A core beat -l INFO"
    volumes:
      - .:/core
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vkpdm#gx$&n^!=9(a9a5^^73!ti9yhrdg09854a@uskrancz5o
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  flower: 
    build: .
    command: celery -A core flower
    ports:
      - 5555:5555
    volumes:
      - .:/core
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vkpdm#gx$&n^!=9(a9a5^^73!ti9yhrdg09854a@uskrancz5o
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
      - celery
      - celery-beat