# Generated by Django 4.2.2 on 2023-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='number',
            field=models.IntegerField(max_length=255, verbose_name='Номер поля'),
        ),
    ]
