# Generated by Django 4.2.2 on 2023-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_field_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_image',
            field=models.ImageField(default=False, upload_to='field_images/', verbose_name='Фото поля'),
        ),
        migrations.AlterField(
            model_name='field',
            name='number',
            field=models.IntegerField(verbose_name='Номер поля'),
        ),
    ]
